# Workflow that lints code, runs tests, and builds the project. On pushes
# to the main branch, also creates a version and create a release on GitHub.
name: CI/CD

# cancel any in-progress runs for the same branch/PR when a new run starts
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test_build_release:
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: INSTALL - node.js, yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: DEBUG - node, npm, yarn versions
        run: |
          echo "node --version: $(node --version)"
          echo "npm --version: $(npm --version)"
          echo "yarn --version: $(yarn --version)"

      - name: CACHE - get yarn cache folder path
        id: yarn-cache-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: CACHE - yarn dependencies
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: INSTALL - dependencies
        run: yarn install

      - name: LINT, TEST
        run: yarn ci

      - name: BUILD
        run: yarn build
        env:
          NODE_ENV: production
          VITE_APP_TITLE: ${{ vars.VITE_APP_TITLE }}
          VITE_AWS_REGION: ${{ vars.VITE_AWS_REGION }}
          VITE_CF_DOMAIN: ${{ vars.VITE_CF_DOMAIN }}
          VITE_IDP_ENABLED: ${{ vars.VITE_IDP_ENABLED }}
          VITE_COGNITO_DOMAIN: ${{ vars.VITE_COGNITO_DOMAIN }}
          VITE_USER_POOL_ID: ${{ vars.VITE_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ vars.VITE_USER_POOL_CLIENT_ID }}
          VITE_COGNITO_REDIRECT_SIGN_IN: ${{ vars.VITE_COGNITO_REDIRECT_SIGN_IN }}
          VITE_COGNITO_REDIRECT_SIGN_OUT: ${{ vars.VITE_COGNITO_REDIRECT_SIGN_OUT }}
          VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ vars.VITE_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_FIRESTORE_CHAT: ${{ vars.VITE_FIREBASE_FIRESTORE_CHAT }}

      # semantic-release will only run on pushes to main (see package.json)
      - name: RELEASE
        run: yarn semantic-release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
